"""Automated submission build: tested src + trained model -> submission notebook.

No hand-copying of source into a notebook, ever.  The notebook embeds
  * a zip of the EXACT `src/sbr` tree that the tests ran against, base64-encoded
  * a zip of the trained model directory, base64-encoded
and unpacks both at run time.  Nothing is transformed, so there is no class of
bug where the notebook and the tested code differ.

Embedded in the notebook and checked at load time:
  source SHA   sha256 over the packed source zip
  model SHA    sha256 over the packed model zip
  feature manifest SHA   from the streaming engine

`ProductionModel.load` re-derives the feature manifest from the unpacked engine
and raises if it does not match the value the model was trained against, so a
mismatched pair fails loudly at import rather than silently scoring nonsense.
"""
from __future__ import annotations

import argparse, base64, hashlib, io, json, os, subprocess, zipfile

ROOT = os.environ.get(
    "SBR_ROOT",
    os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")),
)


def pack_dir(path, arc_prefix, skip_pycache=True):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for d, dirs, fs in os.walk(path):
            if skip_pycache:
                dirs[:] = [x for x in dirs if x != "__pycache__"]
            for f in sorted(fs):
                if f.endswith((".pyc", ".pyo")):
                    continue
                full = os.path.join(d, f)
                z.write(full, os.path.join(arc_prefix, os.path.relpath(full, path)))
    raw = buf.getvalue()
    return raw, hashlib.sha256(raw).hexdigest()


CELL_BOOT = '''\
# ---------------------------------------------------------------------------
# SELF-EXTRACTING PAYLOAD -- generated by research/scripts/build_submission.py
# Do not edit by hand.  Rebuild instead:  python3 research/scripts/build_submission.py
#
#   source zip sha256 : {src_sha}
#   model  zip sha256 : {mdl_sha}
#   feature manifest  : {feat_sha}
#   code git sha      : {git_sha}
#   built at          : {built}
# ---------------------------------------------------------------------------
import base64, hashlib, io, os, sys, zipfile

for _k in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
           "VECLIB_MAXIMUM_THREADS", "NUMEXPR_NUM_THREADS"):
    os.environ.setdefault(_k, "1")

_SRC_B64 = "{src_b64}"
_MDL_B64 = "{mdl_b64}"

_WORK = os.path.abspath(f"./_sbr_payload_{{os.getpid()}}")
os.makedirs(_WORK, exist_ok=True)


def _unpack(b64, expect_sha, name):
    raw = base64.b64decode(b64)
    got = hashlib.sha256(raw).hexdigest()
    if got != expect_sha:
        raise RuntimeError(f"{{name}} payload corrupted: {{got}} != {{expect_sha}}")
    with zipfile.ZipFile(io.BytesIO(raw)) as z:
        z.extractall(_WORK)
    return got


_unpack(_SRC_B64, "{src_sha}", "source")
_unpack(_MDL_B64, "{mdl_sha}", "model")
if _WORK not in sys.path:
    sys.path.insert(0, _WORK)

MODEL_DIRECTORY = os.path.join(_WORK, "model")
print("payload ok; source and model verified by sha256")
'''

CELL_ENTRY = '''\
import os
from typing import Iterable, Iterator, List, Optional, Tuple

# Series are independent by construction -- there is no cross-series state.
# The official macOS Crunch runner segfaults LightGBM under forked P=4 workers,
# so the deployable artifact uses one worker and stays within the time budget.
# @crunch/keep:on
INFER_PARALLELISM = 1

_MODEL = None


def _load_model(model_directory_path: str):
    """Load LightGBM only inside the process that will run inference."""
    global _MODEL
    if _MODEL is None:
        from sbr.production.model import ProductionModel
        _MODEL = ProductionModel.load(model_directory_path)
    return _MODEL


def train(datasets, model_directory_path: str):
    """Install the pre-trained, pre-validated model.

    The model is a frozen function of the training data and was fitted offline
    on the 8,000 development series with the full 500-column causal feature bank
    (see research/REPRODUCIBILITY_MANIFEST.json).  Refitting it inside the
    runner would add an hour of feature construction and a large amount of
    avoidable risk for no change in the resulting function.
    """
    import json
    import shutil
    os.makedirs(model_directory_path, exist_ok=True)
    for f in os.listdir(MODEL_DIRECTORY):
        shutil.copy2(os.path.join(MODEL_DIRECTORY, f), os.path.join(model_directory_path, f))
    with open(os.path.join(model_directory_path, "manifest.json"), "r", encoding="utf-8") as fh:
        manifest = json.load(fh)
    n_models = len(manifest.get("streams") or manifest.get("modules") or [])
    missing = [f"model.txt.{i}" for i in range(n_models)
               if not os.path.exists(os.path.join(model_directory_path, f"model.txt.{i}"))]
    if missing:
        raise RuntimeError(f"missing copied model files: {missing}")


def infer(datasets: Iterable[Tuple[List[float], Iterable[float]]],
          model_directory_path: str):
    """One score per online observation, in order, single pass, causal.

    At online index t this uses only: this series' historical segment and this
    series' online points 0..t.  No other series, no future point, and never
    the online length -- which is unknowable at t and was the leak that
    invalidated the pre-2026-06-08 predictions.
    """
    import numpy as np
    model = _load_model(model_directory_path)

    yield                                      # readiness handshake

    for x_historical, x_online in datasets:
        model.start_series(np.asarray(x_historical, dtype=np.float64))
        for point in x_online:
            yield model.step(float(point))
'''


def nb_cell(kind, src):
    c = {"cell_type": kind, "metadata": {}, "source": src.splitlines(keepends=True)}
    if kind == "code":
        c["outputs"] = []
        c["execution_count"] = None
    return c


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=f"{ROOT}/models/rt100_stream")
    ap.add_argument("--out", default=f"{ROOT}/submissions/rt100_streaming.ipynb")
    ap.add_argument("--title", default="RT-100 streaming (single booster, 500 causal features)")
    a = ap.parse_args()
    os.makedirs(os.path.dirname(a.out), exist_ok=True)

    src_raw, src_sha = pack_dir(f"{ROOT}/src/sbr", "sbr")
    mdl_raw, mdl_sha = pack_dir(a.model, "model")
    man = json.load(open(os.path.join(a.model, "manifest.json")))
    git_sha = subprocess.check_output(["git", "-C", ROOT, "rev-parse", "HEAD"]).decode().strip()
    import time
    boot = CELL_BOOT.format(
        src_sha=src_sha, mdl_sha=mdl_sha, feat_sha=man["feature_manifest_sha256"],
        git_sha=git_sha, built=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        src_b64=base64.b64encode(src_raw).decode(), mdl_b64=base64.b64encode(mdl_raw).decode())

    md = f"""# {a.title}

Structural Break Challenge -- Real-Time Edition.

**Architecture.** One shared incremental feature engine (`sbr.stream.StreamEngine`)
updates {man['n_features']} causal features per observation in O(1) amortised time, feeding
{len(man['booster_columns'])} LightGBM booster(s).

**Causality.** Every feature module is bitwise-identical to a batch implementation
that passes prefix-invariance at `atol=0`, and the full {man['n_features']}-column vector is
bitwise-identical between the streaming and batch paths on real and adversarial
series (`tests/test_stream_engine_parity.py`). Streaming predictions match batch
predictions to 0.0 over 12,727 points end to end.

**No cross-series information.** Scores depend only on this series' history and
its online points up to the current index. The local harness asserts that
shuffling the series order leaves every score unchanged.

**`n_online` is never observed.** Asserted by `tests/test_production_contract.py::test_n_online_is_never_a_feature`.

Built from git `{git_sha[:10]}`, feature manifest `{man['feature_manifest_sha256'][:16]}`.
"""

    nb = {"cells": [nb_cell("markdown", md), nb_cell("code", boot), nb_cell("code", CELL_ENTRY)],
          "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python",
                                      "name": "python3"},
                       "language_info": {"name": "python", "version": "3.11"}},
          "nbformat": 4, "nbformat_minor": 5}
    json.dump(nb, open(a.out, "w"), indent=1)
    print(f"wrote {a.out}  ({os.path.getsize(a.out)/1e6:.1f} MB)")
    print(f"  source sha {src_sha}\n  model  sha {mdl_sha}\n  feature manifest {man['feature_manifest_sha256']}")


if __name__ == "__main__":
    main()
